[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "min_quant"
version = "0.1.0"
description = "A modular quant trading system"
requires-python = ">=3.10"
dependencies = []

[tool.pytest.ini_options]
pythonpath = [
    "src"
]
